        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 24 15:52:42 2020
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE READHYDROBOUNDARYCONDITION__genmod
          INTERFACE 
            SUBROUTINE READHYDROBOUNDARYCONDITION(HYDROPARAM,           &
     &HYDROCONFIGURATION,INITIME,FINALTIME,MESHPARAM)
              USE MESHVARS
              USE DOMAIN_TYPES
              USE HYDRODYNAMIC
              TYPE (HYDRODYNAMICPARAM) :: HYDROPARAM
              TYPE (HYDRODYNAMICCONFIGURATION) :: HYDROCONFIGURATION
              INTEGER(KIND=4) :: INITIME
              INTEGER(KIND=4) :: FINALTIME
              TYPE (MESHGRIDPARAM) :: MESHPARAM
            END SUBROUTINE READHYDROBOUNDARYCONDITION
          END INTERFACE 
        END MODULE READHYDROBOUNDARYCONDITION__genmod
