        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 27 10:42:19 2020
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE READWQBOUNDARYCONDITION__genmod
          INTERFACE 
            SUBROUTINE READWQBOUNDARYCONDITION(MESHPARAM,HYDROPARAM,    &
     &LIMNOPARAM,HYDROCONFIGURATION,WQCONFIGURATION,INITIME,FINALTIME)
              USE DOMAIN_TYPES
              USE LIMNOLOGYVARS
              USE HYDRODYNAMIC
              USE MESHVARS
              TYPE (MESHGRIDPARAM) :: MESHPARAM
              TYPE (HYDRODYNAMICPARAM) :: HYDROPARAM
              TYPE (LIMNOLOGYPARAM) :: LIMNOPARAM
              TYPE (HYDRODYNAMICCONFIGURATION) :: HYDROCONFIGURATION
              TYPE (WATERQUALITYCONFIGURATION) :: WQCONFIGURATION
              INTEGER(KIND=4) :: INITIME
              INTEGER(KIND=4) :: FINALTIME
            END SUBROUTINE READWQBOUNDARYCONDITION
          END INTERFACE 
        END MODULE READWQBOUNDARYCONDITION__genmod
