Subroutine DestroyHydro(HydroParam)

    Use Hydrodynamic
    
	Implicit none
   
    type(HydrodynamicParam) :: HydroParam
    
    Deallocate(HydroParam%Z)
    Deallocate(HydroParam%Ze)
    Deallocate(HydroParam%Zb)
    Deallocate(HydroParam%DZj)
    Deallocate(HydroParam%DZjt)
    Deallocate(HydroParam%DZi)
    Deallocate(HydroParam%DZit)
    Deallocate(HydroParam%iADZ)
    Deallocate(HydroParam%iAG)
    Deallocate(HydroParam%DZiADZ)
    Deallocate(HydroParam%DZiAG)
    Deallocate(HydroParam%Smallm)
    Deallocate(HydroParam%CapitalM)
    Deallocate(HydroParam%ElSmallm)
    Deallocate(HydroParam%ElCapitalM)
    
    Deallocate(HydroParam%etaInf)
    Deallocate(HydroParam%etaplus)
    Deallocate(HydroParam%peta)
    Deallocate(HydroParam%petan)
    Deallocate(HydroParam%eta)
    Deallocate(HydroParam%etan)
    Deallocate(HydroParam%hb)
    Deallocate(HydroParam%H)
    Deallocate(HydroParam%hj)
    Deallocate(HydroParam%u)
    Deallocate(HydroParam%ut)
    Deallocate(HydroParam%uxyback)
    Deallocate(HydroParam%uNode)
    Deallocate(HydroParam%uxy)
    Deallocate(HydroParam%Wu)
    Deallocate(HydroParam%ub)
    Deallocate(HydroParam%w)
    Deallocate(HydroParam%Hu)
    Deallocate(HydroParam%P)
    Deallocate(HydroParam%Aeta)
    Deallocate(HydroParam%f)
    Deallocate(HydroParam%Deta)
    Deallocate(HydroParam%rhs)
    Deallocate(HydroParam%Gu)
    Deallocate(HydroParam%Fu)
    Deallocate(HydroParam%Fv)
    Deallocate(HydroParam%Fuv)
    Deallocate(HydroParam%Fvu)
    Deallocate(HydroParam%FuxyNode)
    Deallocate(HydroParam%Fub)
    Deallocate(HydroParam%Rug)
    Deallocate(HydroParam%uIniVec)
    Deallocate(HydroParam%sDRhoW)
    
    Deallocate(HydroParam%HorViscosity)
    Deallocate(HydroParam%HorDiffusivity)
    Deallocate(HydroParam%VerEddyVisc)
    Deallocate(HydroParam%VerEddyDiff)
    
    Deallocate(HydroParam%WindVel)
    Deallocate(HydroParam%WindXY)
    Deallocate(HydroParam%Windix)
    Deallocate(HydroParam%Windiy)
    Deallocate(HydroParam%InFlowValue)
    Deallocate(HydroParam%WaterLevelValue)
    Deallocate(HydroParam%InFlowTime)
    Deallocate(HydroParam%WaterLevelTime)
    Deallocate(HydroParam%InFlownTime)
    Deallocate(HydroParam%WaterLevelnTime)
    Deallocate(HydroParam%InFlowSmallm)
    Deallocate(HydroParam%InFlowCapitalM)
    Deallocate(HydroParam%IndexWaterLevel)
    Deallocate(HydroParam%IndexInflow)
    Deallocate(HydroParam%WaterLevel)
    Deallocate(HydroParam%fetch_m)
    
    Deallocate(HydroParam%SScalar)
    Deallocate(HydroParam%SScalar2D)
    Deallocate(HydroParam%SVector)
    
    Deallocate(HydroParam%uLoadVarEst)
    Deallocate(HydroParam%dVarEst)
    Deallocate(HydroParam%Locdt)
    Deallocate(HydroParam%DZitau)
    Deallocate(HydroParam%DZistau)
    
    Return
End Subroutine DestroyHydro
	
